pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'github-new',                     
                url: 'https://github.com/niyaz-hasan/Devops-Tasks.git',
                branch: 'main'
           }
        }

        stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "niyazhasan/python:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "./Dockerfile"
        REGISTRY_CREDENTIALS = credentials('docker-cred')
      }
      steps {
        script {
            sh 'cd jenkins/python-jenkins-argocd-k8s && docker build -t ${DOCKER_IMAGE} .'
            def dockerImage = docker.image("${DOCKER_IMAGE}")
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                dockerImage.push()
            }
        }
      }
    }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'github-new', 
                url: 'https://github.com/niyaz-hasan/cicd-Argocd-manifests-repo.git',
                branch: 'main'
            }
        }
        
        stage('Update Deployment File') {
        environment {
            GIT_REPO_NAME = "cicd-Argocd-manifests-repo"
            GIT_USER_NAME = "niyaz-hasan"
        }
        steps {
            withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                sh '''
                    git config user.email "niyazzz1996@gmail.com"
                    git config user.name "niyaz-hasan"
                    BUILD_NUMBER=${BUILD_NUMBER}
                    sed -i '18s/.*/        image:  CONTAINER_IMAGE/' python-app-manifests/deployment.yml
                    sed -i 's@CONTAINER_IMAGE@'"niyazhasan/python:${BUILD_NUMBER}"'@' python-app-manifests/deployment.yml
                    git add .
                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
                '''
            }
                }
            }
        }
    }